# Generated by Django 4.0 on 2022-07-13 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Group_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=225)),
                ('Quantity', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Value', models.IntegerField()),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stock_groups')),
            ],
        ),
    ]
