# Generated by Django 4.0 on 2022-07-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_groups',
            name='Group_total',
            field=models.IntegerField(default=0),
        ),
    ]
